INSERT INTO diseases (class_name, display_name, crop, 
                    description, symptoms, prevention, treatment) 
VALUES
('Potato___Early_blight', 'Potato Early Blight', 'Potato',
 'A fungal leaf disease caused mainly by Alternaria solani. It develops as dark spots and can reduce healthy leaf area.',
 'Small brown to black leaf spots appear, often with clear concentric rings like a target. Older leaves are usually affected first.',
 'Use healthy seed tubers, remove infected crop debris, and follow crop rotation. Keep plants well nourished and avoid stress.',
 'Remove badly infected leaves and plant debris. If disease increases, consult an agriculture expert about a suitable fungicide.'),
('Potato___Late_blight', 'Potato Late Blight', 'Potato',
 'A fast-spreading disease caused by Phytophthora infestans. It is favored by cool, humid and wet conditions.',
 'Water-soaked green to brown or black patches develop on leaves. White growth may appear on the underside in humid weather.',
 'Use healthy seed tubers, provide good drainage, and avoid keeping infected tubers for planting. Remove infected plant material.',
 'Remove infected leaves and tubers and keep the field clean. Consult an agriculture expert about suitable late-blight fungicide management.'),
('Potato___healthy', 'Potato Healthy Leaf', 'Potato',
 'A healthy potato plant has normal green foliage and active growth with no visible disease lesions.',
 'Leaves are evenly green, firm and normally shaped, without dark spots, water-soaked patches, mould or unusual yellowing.',
 'Use healthy seed tubers, maintain good drainage and nutrition, and inspect plants regularly for early disease symptoms.',
 'No disease treatment is needed when the plant is healthy. Continue regular field monitoring and good crop care.'),
('Tomato___Bacterial_spot', 'Tomato Bacterial Spot', 'Tomato',
 'A bacterial disease that commonly develops in wet conditions and can spread by rain splash and infected seed or debris.',
 'Small brown, water-soaked leaf spots appear, often with a yellow halo. Older leaves may develop many spots and drop early.',
 'Use disease-free seed and seedlings, remove crop debris, avoid working with wet plants, and improve air movement around plants.',
 'Remove infected leaves and plant debris. For serious disease, consult an agriculture expert about appropriate bacterial-disease products.'),
('Tomato___Early_blight', 'Tomato Early Blight', 'Tomato',
 'A fungal disease caused by Alternaria solani. It commonly starts on older foliage and can spread during warm, humid weather.',
 'Small dark brown spots enlarge and form concentric rings, giving a bull-eye appearance. Yellowing may occur around the spots.',
 'Use healthy seed, remove infected debris, rotate crops, and avoid prolonged leaf wetness. Keep plants vigorous and well spaced.',
 'Remove infected leaves and crop debris. If symptoms continue to spread, consult an agriculture expert about a suitable fungicide.'),
('Tomato___Late_blight', 'Tomato Late Blight', 'Tomato',
 'A destructive disease caused by Phytophthora infestans that spreads quickly during cool, wet and humid conditions.',
 'Water-soaked dark lesions appear on leaves and stems and enlarge rapidly. White fungal growth may develop on leaf undersides in wet weather.',
 'Provide good drainage, improve air circulation, remove infected debris and avoid unnecessary leaf wetness.',
 'Remove badly infected leaves and plant material. Consult an agriculture expert promptly about suitable late-blight fungicide management.'),
('Tomato___Leaf_Mold', 'Tomato Leaf Mold', 'Tomato',
 'A fungal leaf disease caused by Passalora fulva, especially common where humidity remains high, such as greenhouses and tunnels.',
 'Pale yellow or light-green spots appear on upper leaf surfaces. Olive-green to brown mould develops on the corresponding underside.',
 'Reduce humidity, improve ventilation and air movement, avoid wetting leaves, and remove infected crop debris.',
 'Remove infected leaves and dispose of them safely. For persistent disease, consult an agriculture expert about suitable fungicide options.'),
('Tomato___Septoria_leaf_spot', 'Tomato Septoria Leaf Spot', 'Tomato',
 'A fungal leaf disease caused by Septoria lycopersici. It commonly develops on foliage and can cause early leaf loss.',
 'Many small circular grey spots with dark borders appear on leaves. Tiny dark specks may be visible inside the spots.',
 'Remove infected leaves and crop debris, improve air circulation, and avoid overhead watering or prolonged leaf wetness.',
 'Remove affected leaves and destroy infected plant material. Consult an agriculture expert about suitable fungicide management if needed.'),
('Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato Spider Mites', 'Tomato',
 'A pest problem caused by tiny two-spotted spider mites, especially favored by hot and dry conditions.',
 'Leaves develop many tiny white, yellow or brown speckles. Heavy infestations can cause bronzing, leaf drop and fine webbing.',
 'Check the undersides of leaves regularly, reduce plant stress, and keep the crop adequately watered. Avoid conditions that favor mite buildup.',
 'Wash or remove heavily infested leaves where practical and monitor the crop closely. Consult an agriculture expert about suitable mite-control options.'),
('Tomato___Target_Spot', 'Tomato Target Spot', 'Tomato',
 'A fungal disease caused by Corynespora cassiicola. It can affect leaves, stems and fruit and may cause defoliation.',
 'Small dark leaf lesions enlarge with light-brown centres and darker concentric rings, sometimes with a yellow halo.',
 'Remove infected plant debris, avoid overcrowding, improve air circulation, and reduce prolonged leaf wetness.',
 'Remove badly affected leaves and debris. If the disease spreads, consult an agriculture expert about a suitable fungicide.'),
('Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato Yellow Leaf Curl Virus', 'Tomato',
 'A viral disease commonly spread by whiteflies. It can severely reduce plant growth and fruit production.',
 'Young leaves become small, yellow and curled, often with upward-curled margins. Plants become stunted with shortened growth between nodes.',
 'Use healthy planting material, remove infected plants and weeds, and monitor and control whitefly populations.',
 'Remove infected plants early to reduce spread. There is no simple cure for the virus; consult an agriculture expert for vector-management advice.'),
('Tomato___Tomato_mosaic_virus', 'Tomato Mosaic Virus', 'Tomato',
 'A viral disease that causes green mosaic patterns and distorted growth. It can spread through infected plant material, hands and tools.',
 'Leaves show light and dark green mottling and may become puckered or distorted. Young plants may become pale and stunted.',
 'Use disease-free seed and planting material, remove infected plants, clean tools and avoid spreading sap between plants.',
 'Remove and destroy infected plants because viruses cannot usually be cured after infection. Consult an agriculture expert if diagnosis is uncertain.'),
('Tomato___healthy', 'Tomato Healthy Leaf', 'Tomato',
 'A healthy tomato plant has vigorous growth and normally green, well-shaped leaves without disease or pest damage.',
 'Leaves are green and normally formed, with no unusual spots, mould, mosaic patterns, curling, stippling or severe yellowing.',
 'Use healthy planting material, maintain balanced water and nutrition, provide good airflow, and inspect plants regularly.',
 'No disease treatment is needed when the plant is healthy. Continue routine monitoring and good crop-management practices.');